version: '3'
services:
    flask:
        build: .
        restart: always
        volumes:
            - .:/app
        ports:
            - "5000:5000"
        environment:
            version: 1
            releases: 1a
            